/**
 * Copyright 2014 by Andre Beckus
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at

 *   http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package com.abcodeworks.webshortcututil.read;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

import android.test.AndroidTestCase;
import android.test.suitebuilder.annotation.SmallTest;

import com.abcodeworks.webshortcututil.read.DesktopShortcutReader;
import com.abcodeworks.webshortcututil.read.ShortcutReadException;
import com.abcodeworks.webshortcututil.read.ShortcutReader;

import static com.abcodeworks.webshortcututil.ShortcutTestHelper.testReadShortcut;
import static com.abcodeworks.webshortcututil.ShortcutTestHelper.getTestStream;

public class DesktopShortcutReaderTest extends AndroidTestCase
{
    ShortcutReader reader = null;
    
    final String
        GNOME_PATH = "samples" + File.separator + "real" + File.separator + "desktop" + File.separator + "gnome",
        GNOME_PATH_RENAMED = GNOME_PATH + File.separator + "renamed/",
        KDE_PATH = "samples" + File.separator + "real" + File.separator + "desktop" + File.separator + "kde",
        FAKE_PATH = "samples" + File.separator + "fake" + File.separator + "desktop";
      
    public void setUp() throws Exception {
        reader = new DesktopShortcutReader();
    }

    @SmallTest
    public void testReadUrlString()
                  throws FileNotFoundException,
                         ShortcutReadException,
                         IOException
    {
        // Shortcuts generated by Gnome
        testReadShortcut(reader, GNOME_PATH, "Google.desktop", "Google", "https://www.google.com/");
        testReadShortcut(reader, GNOME_PATH, "Yahoo!.desktop", "Yahoo!", "http://www.yahoo.com/");
        testReadShortcut(reader, GNOME_PATH_RENAMED,  "Link to Google - renamed.desktop", "Link to Google - renamed", "https://www.google.com/");
        
        // Shortcuts generated by KDE
        testReadShortcut(reader, KDE_PATH, "http___japan.zdnet.com_.desktop", "http___japan.zdnet.com_", "http://japan.zdnet.com/");
        testReadShortcut(reader, KDE_PATH, "https___www.google.com_.desktop", "https___www.google.com_", "https://www.google.com/");
        testReadShortcut(reader, KDE_PATH, "http___www.microsoft.com_sv-se_default.aspx.desktop", "http___www.microsoft.com_sv-se_default.aspx", "http://www.microsoft.com/sv-se/default.aspx");
        testReadShortcut(reader, KDE_PATH, "http___www.myspace.com_.desktop", "http___www.myspace.com_", "http://www.myspace.com/");
        testReadShortcut(reader, KDE_PATH, "http___www.yahoo.com_.desktop", "http___www.yahoo.com_", "http://www.yahoo.com/");
        testReadShortcut(reader, KDE_PATH, "http___cn.yahoo.com_.desktop", "http___cn.yahoo.com_", "http://cn.yahoo.com/");
        testReadShortcut(reader, KDE_PATH, "http___xn--fet810g.xn--fiqs8s_.desktop", "http___xn--fet810g.xn--fiqs8s_", "http://xn--fet810g.xn--fiqs8s/");
        testReadShortcut(reader, KDE_PATH, "http___www.baidu.com_.desktop", "http___www.baidu.com_", "http://www.baidu.com/");
        
        // Fake shortcuts
        testReadShortcut(reader, FAKE_PATH, "CommentsAndBlankLines.desktop", "CommentsAndBlankLines", "https://www.google.com/");
        testReadShortcut(reader, FAKE_PATH, "GarbledEntry.desktop", "GarbledEntry", "https://www.google.com/");
        testReadShortcut(reader, FAKE_PATH, "LotsOfWhitespace.desktop", "LotsOfWhitespace", "https://www.google.com/");
    }
}
